# Generated by Django 5.2.4 on 2026-09-30 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principais', '0002_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoOFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('hash_arquivo', models.CharField(help_text='SHA-256 do conteúdo — barra reimportação duplicada.', max_length=64, unique=True, verbose_name='Hash do arquivo')),
                ('conta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conta (ACCTID)')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Início do período')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim do período')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
            ],
            options={
                'verbose_name': 'Extrato OFX',
                'verbose_name_plural': 'Extratos OFX',
                'db_table': 'extratos_ofx',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoOFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitid', models.CharField(help_text='Identificador único da transação no banco (idempotência).', max_length=100, unique=True, verbose_name='FITID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('nome_pagador', models.CharField(max_length=255, verbose_name='Pagador (cru)')),
                ('nome_normalizado', models.CharField(blank=True, default='', help_text="Sem o prefixo 'Recebimento Pix', sem acentos e em caixa baixa.", max_length=255, verbose_name='Pagador (normalizado)')),
                ('memo', models.CharField(blank=True, default='', max_length=255, verbose_name='Memo')),
                ('status_conciliacao', models.CharField(choices=[('CONCILIADO', 'Conciliado'), ('NAO_IDENTIFICADO', 'Não identificado')], default='NAO_IDENTIFICADO', max_length=20, verbose_name='Status da conciliação')),
                ('valor_divergente', models.BooleanField(default=False, help_text='Casou o paciente, mas o valor difere do combinado (decisão #15).', verbose_name='Valor divergente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='conciliacao.extratoofx', verbose_name='Extrato')),
                ('fk_paciente', models.ForeignKey(blank=True, db_column='fk_paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='principais.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Transação OFX',
                'verbose_name_plural': 'Transações OFX',
                'db_table': 'transacoes_ofx',
                'ordering': ['-data', 'nome_pagador'],
            },
        ),
    ]
