# Generated by Django 5.2.4 on 2026-09-30 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principais', '0002_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_competencia', models.DateField(help_text='Primeiro dia do mês de competência (mês anterior ao fechamento).', verbose_name='Competência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('status_nfs', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('EMITIDA', 'Emitida'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status da NFS-e')),
                ('id_nfs', models.CharField(blank=True, max_length=64, null=True, verbose_name='UUID Webmania')),
                ('motivo_erro', models.TextField(blank=True, default='', verbose_name='Motivo do erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_paciente', models.ForeignKey(db_column='fk_paciente', on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='principais.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'db_table': 'notas_fiscais',
                'ordering': ['-mes_competencia', 'fk_paciente__nome'],
                'unique_together': {('fk_paciente', 'mes_competencia')},
            },
        ),
    ]
