# Generated by Django 5.2.4 on 2026-09-30 23:08

import django.core.validators
import django.db.models.deletion
import principais.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abordagem',
            fields=[
                ('pk_abordagem', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('abordagem', models.CharField(max_length=255, verbose_name='Abordagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Abordagem',
                'verbose_name_plural': 'Abordagens',
                'db_table': 'abordagens',
                'ordering': ['abordagem'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('pk_tag', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('horas_consumidas', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional: horas da capacidade do terapeuta que esta tag consome.', max_digits=5, null=True, verbose_name='Horas consumidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('pk_associado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Informe um endereço de e-mail válido.')], verbose_name='E-mail')),
                ('telefone', models.CharField(help_text='Exemplo: 31988553344 (sem +55/espaços/parênteses)', max_length=20, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos. Exemplo: 31988553344', regex='^\\d{10,11}$')], verbose_name='Telefone')),
                ('contato_apoio', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos. Exemplo: 31988553344', regex='^\\d{10,11}$')], verbose_name='Telefone do Contato de Apoio')),
                ('dat_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Sexo')),
                ('cpf', models.CharField(blank=True, help_text='Só números. Exemplo: 12345678901', max_length=14, null=True, unique=True, validators=[principais.models.validar_cpf], verbose_name='CPF')),
                ('endereco', models.CharField(blank=True, help_text='Exemplo: MG, Belo Horizonte', max_length=100, null=True, verbose_name='Endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.OneToOneField(blank=True, help_text='Usuário de login vinculado ao associado (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Associado',
                'verbose_name_plural': 'Associados',
                'db_table': 'associados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('pk_terapeuta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('pacientes_max', models.IntegerField(blank=True, null=True, verbose_name='Máximo de pacientes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('link_agenda', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Agenda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('fk_abordagem', models.ForeignKey(blank=True, db_column='fk_abordagem', null=True, on_delete=django.db.models.deletion.PROTECT, to='principais.abordagem', verbose_name='Abordagem')),
                ('fk_associado', models.ForeignKey(db_column='fk_associado', on_delete=django.db.models.deletion.CASCADE, to='principais.associado', verbose_name='Associado')),
                ('fk_supervisor', models.ForeignKey(blank=True, db_column='fk_supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisionados', to='principais.terapeuta', verbose_name='Supervisor')),
                ('tags', models.ManyToManyField(blank=True, db_table='terapeutas_tags', related_name='terapeutas_atuais', to='principais.tag', verbose_name='Tags atuais')),
                ('tags_apto', models.ManyToManyField(blank=True, db_table='terapeutas_tags_apto', related_name='terapeutas_aptos', to='principais.tag', verbose_name='Apto a')),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeutas',
                'db_table': 'terapeutas',
                'ordering': ['fk_associado__nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('pk_paciente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Informe um endereço de e-mail válido.')], verbose_name='E-mail')),
                ('telefone', models.CharField(help_text='Exemplo: 31988553344 (sem +55/espaços/parênteses)', max_length=20, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos. Exemplo: 31988553344', regex='^\\d{10,11}$')], verbose_name='Telefone do Paciente')),
                ('contato_apoio', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos. Exemplo: 31988553344', regex='^\\d{10,11}$')], verbose_name='Telefone do Contato de Apoio')),
                ('dat_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('vlr_sessao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Acordado')),
                ('origem', models.CharField(blank=True, help_text='De onde veio o paciente (substitui a antiga captação).', max_length=100, null=True, verbose_name='Origem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status_atendimento', models.CharField(choices=[('AGUARDANDO_INICIO', 'Aguardando Início'), ('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='AGUARDANDO_INICIO', max_length=20, verbose_name='Status do Atendimento')),
                ('origem_paciente', models.CharField(choices=[('NOVO', 'Novo Paciente'), ('REENCAMINHADO', 'Reencaminhado')], default='NOVO', max_length=20, verbose_name='Origem do Paciente')),
                ('dia_semana_padrao', models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Dia Padrão da Sessão')),
                ('hora_padrao', models.TimeField(blank=True, null=True, validators=[principais.models.validate_minutes], verbose_name='Horário Padrão da Sessão')),
                ('cpf', models.CharField(blank=True, help_text='Só números. Exemplo: 12345678901', max_length=14, null=True, unique=True, validators=[principais.models.validar_cpf], verbose_name='CPF')),
                ('cep', models.CharField(blank=True, help_text='Apenas números', max_length=9, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, default='Belo Horizonte', max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='MG', max_length=2, null=True, verbose_name='UF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('fk_terapeuta', models.ForeignKey(blank=True, db_column='fk_terapeuta', help_text='Vazio = paciente aguardando encaminhamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='principais.terapeuta', verbose_name='Terapeuta')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(validators=[principais.models.validate_minutes], verbose_name='Horário de início')),
                ('hora_fim', models.TimeField(validators=[principais.models.validate_minutes], verbose_name='Horário de fim')),
                ('fk_terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='principais.terapeuta')),
            ],
            options={
                'verbose_name': 'Horário Disponível',
                'verbose_name_plural': 'Horários Disponíveis',
                'ordering': ['fk_terapeuta', 'dia_semana', 'hora_inicio'],
                'unique_together': {('fk_terapeuta', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
