# Generated by Django 5.2.4 on 2026-10-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principais', '0002_notificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='status_atendimento',
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='fk_tag',
            field=models.ForeignKey(blank=True, help_text='Vazio = disponível para pacientes. Preenchido = bloco desta atividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocos', to='principais.tag', verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='tag',
            name='descricao',
            field=models.TextField(blank=True, help_text="O que é a atividade (ex.: 'grupo de estudo toda terça').", null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='horas_consumidas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duração sugerida da atividade ao alocá-la no calendário do terapeuta.', max_digits=5, null=True, verbose_name='Tempo padrão (h)'),
        ),
    ]
