# Generated by Django 5.2.4 on 2026-10-03 18:13

import django.db.models.deletion
import principais.models
from django.db import migrations, models


def copiar_sessoes(apps, schema_editor):
    """Move o par dia_semana_padrao/hora_padrao de cada paciente para uma
    SessaoSemanal (quando ambos estavam preenchidos)."""
    Paciente = apps.get_model('principais', 'Paciente')
    SessaoSemanal = apps.get_model('principais', 'SessaoSemanal')
    for p in Paciente.objects.exclude(dia_semana_padrao=None).exclude(hora_padrao=None):
        SessaoSemanal.objects.get_or_create(
            fk_paciente_id=p.pk,
            dia_semana=p.dia_semana_padrao,
            hora_inicio=p.hora_padrao,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('principais', '0003_remove_paciente_status_atendimento_and_more'),
    ]

    operations = [
        # 1) Cria a tabela nova.
        migrations.CreateModel(
            name='SessaoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(validators=[principais.models.validate_minutes], verbose_name='Horário')),
                ('fk_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='principais.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Sessão Semanal',
                'verbose_name_plural': 'Sessões Semanais',
                'db_table': 'sessoes_semanais',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('fk_paciente', 'dia_semana', 'hora_inicio')},
            },
        ),
        # 2) Copia os horários existentes para a tabela nova.
        migrations.RunPython(copiar_sessoes, noop),
        # 3) Remove os campos antigos do paciente.
        migrations.RemoveField(model_name='paciente', name='dia_semana_padrao'),
        migrations.RemoveField(model_name='paciente', name='hora_padrao'),
    ]
