# Generated by Django 5.2.4 on 2026-10-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principais', '0004_remove_paciente_dia_semana_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagadorAlternativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do pagador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagadores', to='principais.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Pagador alternativo',
                'verbose_name_plural': 'Pagadores alternativos',
                'db_table': 'pagadores_alternativos',
                'ordering': ['nome'],
            },
        ),
    ]
