# Generated by Django 5.2.4 on 2026-10-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principais', '0005_pagadoralternativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_primeiro_pagamento',
            field=models.DateField(blank=True, help_text='Data em que o primeiro Pix caiu. O dia recorrente é derivado dela — é só uma EXPECTATIVA para ajudar a conciliação/atraso; quem confirma pagamento é sempre o OFX (decisão #3).', null=True, verbose_name='Data do 1º pagamento'),
        ),
    ]
